# Generated by Django 4.1.7 on 2023-03-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25, verbose_name='User name')),
                ('user_nickname', models.CharField(max_length=255, verbose_name='User nickname')),
                ('user_email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('user_password', models.CharField(max_length=255, verbose_name='User password')),
                ('user_photo', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
